environment:
  matrix:
    - ARCH: x86_64
      ABI: gnu
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
    - ARCH: x86_64
      ABI: msvc
      CHANNEL: nightly
      EXTRA_FEATURES: clippy
install:
  - SET PATH=%PATH%;%USERPROFILE%\.cargo\bin;C:\MinGW\bin
  - SET TARGET=%ARCH%-pc-windows-%ABI%
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe"
  - rustup-init.exe -y --no-modify-path --default-host %TARGET% --default-toolchain %CHANNEL%
  - rustup -vV
  - rustc -vV
  - rustdoc -vV
  - cargo -vV
build_script:
  - cargo build -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
  - cargo doc -vv --target=%TARGET% --features = "%EXTRA_FEATURES%"
test_script:
  - cargo test -vv --target=%TARGET% --features "%EXTRA_FEATURES%"
